### ISSUE TITLE
Panic when rendering

### ISSUE THREAD

**Issue by jdm** [jdm/mzxscreen#6]
https://www.digitalmzx.com/show.php?id=497
```
thread 'main' panicked at 'range end index 672024 out of range for slice of length 672000', capture/src/main.rs:23:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/81dc88f88f92ba8ad7465f9cba10c12d3a7b70f1/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/81dc88f88f92ba8ad7465f9cba10c12d3a7b70f1/library/core/src/panicking.rs:85
   2: core::slice::slice_end_index_len_fail
             at /rustc/81dc88f88f92ba8ad7465f9cba10c12d3a7b70f1/library/core/src/slice/mod.rs:3152
   3: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index_mut
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/mod.rs:3352
   4: core::slice::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/mod.rs:3137
   5: <capture::Framebuffer as libmzx::render::Renderer>::put_pixel
             at ./capture/src/main.rs:23
   6: libmzx::render::draw_char
             at /Users/jdm/src/libmzx/src/render.rs:606
   7: libmzx::render::render
             at /Users/jdm/src/libmzx/src/render.rs:203
   8: capture::render_game
             at ./capture/src/main.rs:198
   9: capture::run
             at ./capture/src/main.rs:153
  10: capture::main
             at ./capture/src/main.rs:220
  11: core::ops::function::FnOnce::call_once
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:233
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jdm** [comment]
Fixed by https://github.com/jdm/libmzx/commit/56ade15ed026fd6931a5e0e43cf7bc20c542a0ba
